# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QRev_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 700)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        MainWindow.setPalette(palette)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tab_all = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_all.sizePolicy().hasHeightForWidth())
        self.tab_all.setSizePolicy(sizePolicy)
        self.tab_all.setSizeIncrement(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tab_all.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_all.setFont(font)
        self.tab_all.setAutoFillBackground(False)
        self.tab_all.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_all.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_all.setIconSize(QtCore.QSize(40, 24))
        self.tab_all.setObjectName("tab_all")
        self.tab_main = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_main.sizePolicy().hasHeightForWidth())
        self.tab_main.setSizePolicy(sizePolicy)
        self.tab_main.setObjectName("tab_main")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_main)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_summary = QtWidgets.QTabWidget(self.tab_main)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.tab_summary.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_summary.setFont(font)
        self.tab_summary.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_summary.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_summary.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_summary.setObjectName("tab_summary")
        self.tab_summary_discharge = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_summary_discharge.sizePolicy().hasHeightForWidth())
        self.tab_summary_discharge.setSizePolicy(sizePolicy)
        self.tab_summary_discharge.setObjectName("tab_summary_discharge")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_summary_discharge)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_table_summary = QtWidgets.QTableWidget(self.tab_summary_discharge)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.main_table_summary.setFont(font)
        self.main_table_summary.setAutoFillBackground(False)
        self.main_table_summary.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.main_table_summary.setObjectName("main_table_summary")
        self.main_table_summary.setColumnCount(0)
        self.main_table_summary.setRowCount(0)
        self.gridLayout_2.addWidget(self.main_table_summary, 0, 0, 1, 1)
        self.tab_summary.addTab(self.tab_summary_discharge, "")
        self.tab_summary_details = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_summary_details.sizePolicy().hasHeightForWidth())
        self.tab_summary_details.setSizePolicy(sizePolicy)
        self.tab_summary_details.setObjectName("tab_summary_details")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_summary_details)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.main_table_details = QtWidgets.QTableWidget(self.tab_summary_details)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.main_table_details.setFont(font)
        self.main_table_details.setObjectName("main_table_details")
        self.main_table_details.setColumnCount(0)
        self.main_table_details.setRowCount(0)
        self.gridLayout_4.addWidget(self.main_table_details, 0, 0, 1, 1)
        self.tab_summary.addTab(self.tab_summary_details, "")
        self.tab_summary_premeasurement = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_summary_premeasurement.sizePolicy().hasHeightForWidth())
        self.tab_summary_premeasurement.setSizePolicy(sizePolicy)
        self.tab_summary_premeasurement.setObjectName("tab_summary_premeasurement")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_summary_premeasurement)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_summary_premeasurement)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.ed_site_name = QtWidgets.QLineEdit(self.tab_summary_premeasurement)
        self.ed_site_name.setObjectName("ed_site_name")
        self.horizontalLayout_3.addWidget(self.ed_site_name)
        self.label_2 = QtWidgets.QLabel(self.tab_summary_premeasurement)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.ed_site_number = QtWidgets.QLineEdit(self.tab_summary_premeasurement)
        self.ed_site_number.setObjectName("ed_site_number")
        self.horizontalLayout_3.addWidget(self.ed_site_number)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 5)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.table_premeas = QtWidgets.QTableWidget(self.tab_summary_premeasurement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_premeas.setFont(font)
        self.table_premeas.setObjectName("table_premeas")
        self.table_premeas.setColumnCount(0)
        self.table_premeas.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.table_premeas)
        self.horizontalLayout_5.setStretch(0, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.txt_site_name = QtWidgets.QLabel(self.tab_summary_premeasurement)
        self.txt_site_name.setText("")
        self.txt_site_name.setObjectName("txt_site_name")
        self.gridLayout_7.addWidget(self.txt_site_name, 0, 1, 1, 1)
        self.tab_summary.addTab(self.tab_summary_premeasurement, "")
        self.tab_summary_settings = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_summary_settings.sizePolicy().hasHeightForWidth())
        self.tab_summary_settings.setSizePolicy(sizePolicy)
        self.tab_summary_settings.setObjectName("tab_summary_settings")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_summary_settings)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.table_settings = QtWidgets.QTableWidget(self.tab_summary_settings)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.table_settings.setFont(font)
        self.table_settings.setObjectName("table_settings")
        self.table_settings.setColumnCount(0)
        self.table_settings.setRowCount(0)
        self.gridLayout_5.addWidget(self.table_settings, 0, 0, 1, 1)
        self.tab_summary.addTab(self.tab_summary_settings, "")
        self.tab_summary_adcp = QtWidgets.QWidget()
        self.tab_summary_adcp.setObjectName("tab_summary_adcp")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_summary_adcp)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.table_adcp = QtWidgets.QTableWidget(self.tab_summary_adcp)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_adcp.setFont(font)
        self.table_adcp.setObjectName("table_adcp")
        self.table_adcp.setColumnCount(0)
        self.table_adcp.setRowCount(0)
        self.gridLayout_6.addWidget(self.table_adcp, 0, 0, 1, 1)
        self.tab_summary.addTab(self.tab_summary_adcp, "")
        self.verticalLayout.addWidget(self.tab_summary)
        self.graphics_main_middle = QtWidgets.QWidget(self.tab_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics_main_middle.sizePolicy().hasHeightForWidth())
        self.graphics_main_middle.setSizePolicy(sizePolicy)
        self.graphics_main_middle.setMinimumSize(QtCore.QSize(500, 200))
        self.graphics_main_middle.setAutoFillBackground(True)
        self.graphics_main_middle.setObjectName("graphics_main_middle")
        self.verticalLayout.addWidget(self.graphics_main_middle)
        self.horizontalLayout_bottom = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bottom.setObjectName("horizontalLayout_bottom")
        self.tab_mc = QtWidgets.QTabWidget(self.tab_main)
        self.tab_mc.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_mc.setObjectName("tab_mc")
        self.tab_mc_messages = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_mc_messages.sizePolicy().hasHeightForWidth())
        self.tab_mc_messages.setSizePolicy(sizePolicy)
        self.tab_mc_messages.setObjectName("tab_mc_messages")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_mc_messages)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.main_message_table = QtWidgets.QTableWidget(self.tab_mc_messages)
        self.main_message_table.setObjectName("main_message_table")
        self.main_message_table.setColumnCount(0)
        self.main_message_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.main_message_table, 0, 0, 1, 1)
        self.tab_mc.addTab(self.tab_mc_messages, "")
        self.tab_mc_comments = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_mc_comments.sizePolicy().hasHeightForWidth())
        self.tab_mc_comments.setSizePolicy(sizePolicy)
        self.tab_mc_comments.setObjectName("tab_mc_comments")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_mc_comments)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.display_comments = QtWidgets.QPlainTextEdit(self.tab_mc_comments)
        self.display_comments.setReadOnly(True)
        self.display_comments.setObjectName("display_comments")
        self.horizontalLayout_2.addWidget(self.display_comments)
        self.tab_mc.addTab(self.tab_mc_comments, "")
        self.horizontalLayout_bottom.addWidget(self.tab_mc)
        self.graphics_main_timeseries = QtWidgets.QWidget(self.tab_main)
        self.graphics_main_timeseries.setObjectName("graphics_main_timeseries")
        self.horizontalLayout_bottom.addWidget(self.graphics_main_timeseries)
        self.horizontalLayout_bottom.setStretch(0, 4)
        self.horizontalLayout_bottom.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_bottom)
        self.verticalLayout.setStretch(2, 2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.table_qa = QtWidgets.QTableWidget(self.tab_main)
        self.table_qa.setObjectName("table_qa")
        self.table_qa.setColumnCount(0)
        self.table_qa.setRowCount(0)
        self.verticalLayout_right.addWidget(self.table_qa)
        self.table_uncertainty = QtWidgets.QTableWidget(self.tab_main)
        self.table_uncertainty.setObjectName("table_uncertainty")
        self.table_uncertainty.setColumnCount(0)
        self.table_uncertainty.setRowCount(0)
        self.verticalLayout_right.addWidget(self.table_uncertainty)
        self.graphics_main_extrap = QtWidgets.QWidget(self.tab_main)
        self.graphics_main_extrap.setObjectName("graphics_main_extrap")
        self.verticalLayout_right.addWidget(self.graphics_main_extrap)
        self.verticalLayout_right.setStretch(0, 3)
        self.verticalLayout_right.setStretch(1, 5)
        self.verticalLayout_right.setStretch(2, 6)
        self.horizontalLayout.addLayout(self.verticalLayout_right)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tab_all.addTab(self.tab_main, "")
        self.tab_systest = QtWidgets.QWidget()
        self.tab_systest.setObjectName("tab_systest")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_systest)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tab_systest_2 = QtWidgets.QTabWidget(self.tab_systest)
        self.tab_systest_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_systest_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_systest_2.setObjectName("tab_systest_2")
        self.tab_systest_2_results = QtWidgets.QWidget()
        self.tab_systest_2_results.setObjectName("tab_systest_2_results")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_systest_2_results)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.table_systest = QtWidgets.QTableWidget(self.tab_systest_2_results)
        self.table_systest.setObjectName("table_systest")
        self.table_systest.setColumnCount(0)
        self.table_systest.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.table_systest)
        self.display_systest = QtWidgets.QPlainTextEdit(self.tab_systest_2_results)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.display_systest.setFont(font)
        self.display_systest.setObjectName("display_systest")
        self.horizontalLayout_6.addWidget(self.display_systest)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 3)
        self.gridLayout_8.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.tab_systest_2.addTab(self.tab_systest_2_results, "")
        self.tab_systest_2_messages = QtWidgets.QWidget()
        self.tab_systest_2_messages.setObjectName("tab_systest_2_messages")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_systest_2_messages)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.box_systest_messages = QtWidgets.QGroupBox(self.tab_systest_2_messages)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.box_systest_messages.setFont(font)
        self.box_systest_messages.setObjectName("box_systest_messages")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.box_systest_messages)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.display_systest_messages = QtWidgets.QPlainTextEdit(self.box_systest_messages)
        self.display_systest_messages.setObjectName("display_systest_messages")
        self.horizontalLayout_7.addWidget(self.display_systest_messages)
        self.verticalLayout_3.addWidget(self.box_systest_messages)
        self.box_systest_comments = QtWidgets.QGroupBox(self.tab_systest_2_messages)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.box_systest_comments.setFont(font)
        self.box_systest_comments.setObjectName("box_systest_comments")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.box_systest_comments)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.display_systest_comments = QtWidgets.QPlainTextEdit(self.box_systest_comments)
        self.display_systest_comments.setObjectName("display_systest_comments")
        self.horizontalLayout_8.addWidget(self.display_systest_comments)
        self.verticalLayout_3.addWidget(self.box_systest_comments)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tab_systest_2.addTab(self.tab_systest_2_messages, "")
        self.gridLayout_10.addWidget(self.tab_systest_2, 0, 0, 1, 1)
        self.tab_all.addTab(self.tab_systest, "")
        self.tab_compass = QtWidgets.QWidget()
        self.tab_compass.setObjectName("tab_compass")
        self.tab_compass_2 = QtWidgets.QTabWidget(self.tab_compass)
        self.tab_compass_2.setGeometry(QtCore.QRect(0, 10, 1041, 571))
        self.tab_compass_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_compass_2.setObjectName("tab_compass_2")
        self.tab_compass_2_data = QtWidgets.QWidget()
        self.tab_compass_2_data.setObjectName("tab_compass_2_data")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_compass_2_data)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.table_compass_pr = QtWidgets.QTableWidget(self.tab_compass_2_data)
        self.table_compass_pr.setObjectName("table_compass_pr")
        self.table_compass_pr.setColumnCount(0)
        self.table_compass_pr.setRowCount(0)
        self.verticalLayout_6.addWidget(self.table_compass_pr)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.graph_heading = QtWidgets.QWidget(self.tab_compass_2_data)
        self.graph_heading.setObjectName("graph_heading")
        self.horizontalLayout_10.addWidget(self.graph_heading)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cb_adcp_compass = QtWidgets.QCheckBox(self.tab_compass_2_data)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.cb_adcp_compass.setPalette(palette)
        self.cb_adcp_compass.setObjectName("cb_adcp_compass")
        self.verticalLayout_4.addWidget(self.cb_adcp_compass)
        self.cb_ext_compass = QtWidgets.QCheckBox(self.tab_compass_2_data)
        self.cb_ext_compass.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cb_ext_compass.setPalette(palette)
        self.cb_ext_compass.setObjectName("cb_ext_compass")
        self.verticalLayout_4.addWidget(self.cb_ext_compass)
        self.cb_mag_field = QtWidgets.QCheckBox(self.tab_compass_2_data)
        self.cb_mag_field.setEnabled(False)
        self.cb_mag_field.setObjectName("cb_mag_field")
        self.verticalLayout_4.addWidget(self.cb_mag_field)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.horizontalLayout_10.setStretch(0, 10)
        self.horizontalLayout_10.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.graph_pr = QtWidgets.QWidget(self.tab_compass_2_data)
        self.graph_pr.setObjectName("graph_pr")
        self.horizontalLayout_9.addWidget(self.graph_pr)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cb_pitch = QtWidgets.QCheckBox(self.tab_compass_2_data)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cb_pitch.setPalette(palette)
        self.cb_pitch.setObjectName("cb_pitch")
        self.verticalLayout_5.addWidget(self.cb_pitch)
        self.cb_roll = QtWidgets.QCheckBox(self.tab_compass_2_data)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.cb_roll.setPalette(palette)
        self.cb_roll.setObjectName("cb_roll")
        self.verticalLayout_5.addWidget(self.cb_roll)
        self.verticalLayout_5.setStretch(0, 9)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.horizontalLayout_9.setStretch(0, 10)
        self.horizontalLayout_9.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.setStretch(0, 3)
        self.verticalLayout_6.setStretch(1, 4)
        self.verticalLayout_6.setStretch(2, 4)
        self.gridLayout_11.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tab_compass_2.addTab(self.tab_compass_2_data, "")
        self.tab_compass_2_cal = QtWidgets.QWidget()
        self.tab_compass_2_cal.setObjectName("tab_compass_2_cal")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_compass_2_cal)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_cal = QtWidgets.QGroupBox(self.tab_compass_2_cal)
        self.groupBox_cal.setObjectName("groupBox_cal")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_cal)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.table_compass_cal = QtWidgets.QTableWidget(self.groupBox_cal)
        self.table_compass_cal.setObjectName("table_compass_cal")
        self.table_compass_cal.setColumnCount(0)
        self.table_compass_cal.setRowCount(0)
        self.gridLayout_12.addWidget(self.table_compass_cal, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_cal)
        self.groupBox_eval = QtWidgets.QGroupBox(self.tab_compass_2_cal)
        self.groupBox_eval.setObjectName("groupBox_eval")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_eval)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.table_compass_eval = QtWidgets.QTableWidget(self.groupBox_eval)
        self.table_compass_eval.setObjectName("table_compass_eval")
        self.table_compass_eval.setColumnCount(0)
        self.table_compass_eval.setRowCount(0)
        self.gridLayout_13.addWidget(self.table_compass_eval, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_eval)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.display_compass_result = QtWidgets.QTextEdit(self.tab_compass_2_cal)
        self.display_compass_result.setObjectName("display_compass_result")
        self.horizontalLayout_11.addWidget(self.display_compass_result)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 2)
        self.gridLayout_14.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.tab_compass_2.addTab(self.tab_compass_2_cal, "")
        self.tab_compass_2_messages = QtWidgets.QWidget()
        self.tab_compass_2_messages.setObjectName("tab_compass_2_messages")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_compass_2_messages)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.box_compass_messages = QtWidgets.QGroupBox(self.tab_compass_2_messages)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.box_compass_messages.setFont(font)
        self.box_compass_messages.setObjectName("box_compass_messages")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.box_compass_messages)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.display_compass_messages = QtWidgets.QPlainTextEdit(self.box_compass_messages)
        self.display_compass_messages.setObjectName("display_compass_messages")
        self.horizontalLayout_12.addWidget(self.display_compass_messages)
        self.verticalLayout_8.addWidget(self.box_compass_messages)
        self.box_compass_comments = QtWidgets.QGroupBox(self.tab_compass_2_messages)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.box_compass_comments.setFont(font)
        self.box_compass_comments.setObjectName("box_compass_comments")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.box_compass_comments)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.display_compass_comments = QtWidgets.QPlainTextEdit(self.box_compass_comments)
        self.display_compass_comments.setObjectName("display_compass_comments")
        self.horizontalLayout_13.addWidget(self.display_compass_comments)
        self.verticalLayout_8.addWidget(self.box_compass_comments)
        self.gridLayout_15.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.tab_compass_2.addTab(self.tab_compass_2_messages, "")
        self.tab_all.addTab(self.tab_compass, "")
        self.tab_tempsal = QtWidgets.QWidget()
        self.tab_tempsal.setObjectName("tab_tempsal")
        self.tab_tempsal_2 = QtWidgets.QTabWidget(self.tab_tempsal)
        self.tab_tempsal_2.setGeometry(QtCore.QRect(0, 10, 1221, 571))
        self.tab_tempsal_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_tempsal_2.setObjectName("tab_tempsal_2")
        self.tab_tempsal_2_data = QtWidgets.QWidget()
        self.tab_tempsal_2_data.setObjectName("tab_tempsal_2_data")
        self.tab_tempsal_2.addTab(self.tab_tempsal_2_data, "")
        self.tab_tempsal_2_messages = QtWidgets.QWidget()
        self.tab_tempsal_2_messages.setObjectName("tab_tempsal_2_messages")
        self.tab_tempsal_2.addTab(self.tab_tempsal_2_messages, "")
        self.tab_all.addTab(self.tab_tempsal, "")
        self.tab_mbt = QtWidgets.QWidget()
        self.tab_mbt.setObjectName("tab_mbt")
        self.tab_mtb_2 = QtWidgets.QTabWidget(self.tab_mbt)
        self.tab_mtb_2.setGeometry(QtCore.QRect(0, 10, 1231, 571))
        self.tab_mtb_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_mtb_2.setObjectName("tab_mtb_2")
        self.tab_mbt_2_data = QtWidgets.QWidget()
        self.tab_mbt_2_data.setObjectName("tab_mbt_2_data")
        self.tab_mtb_2.addTab(self.tab_mbt_2_data, "")
        self.tab_mbt_2_messages = QtWidgets.QWidget()
        self.tab_mbt_2_messages.setObjectName("tab_mbt_2_messages")
        self.tab_mtb_2.addTab(self.tab_mbt_2_messages, "")
        self.tab_all.addTab(self.tab_mbt, "")
        self.tab_bt = QtWidgets.QWidget()
        self.tab_bt.setObjectName("tab_bt")
        self.tab_bt_2 = QtWidgets.QTabWidget(self.tab_bt)
        self.tab_bt_2.setGeometry(QtCore.QRect(0, 0, 1231, 601))
        self.tab_bt_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_bt_2.setObjectName("tab_bt_2")
        self.tab_bt_2_data = QtWidgets.QWidget()
        self.tab_bt_2_data.setObjectName("tab_bt_2_data")
        self.tab_bt_2.addTab(self.tab_bt_2_data, "")
        self.tab_bt_2_messages = QtWidgets.QWidget()
        self.tab_bt_2_messages.setObjectName("tab_bt_2_messages")
        self.tab_bt_2.addTab(self.tab_bt_2_messages, "")
        self.tab_all.addTab(self.tab_bt, "")
        self.tab_gps = QtWidgets.QWidget()
        self.tab_gps.setObjectName("tab_gps")
        self.tab_gps_2 = QtWidgets.QTabWidget(self.tab_gps)
        self.tab_gps_2.setGeometry(QtCore.QRect(0, 0, 1231, 601))
        self.tab_gps_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_gps_2.setObjectName("tab_gps_2")
        self.tab_gps_2_data = QtWidgets.QWidget()
        self.tab_gps_2_data.setObjectName("tab_gps_2_data")
        self.tab_gps_2.addTab(self.tab_gps_2_data, "")
        self.tab_gps_2_messages_2 = QtWidgets.QWidget()
        self.tab_gps_2_messages_2.setObjectName("tab_gps_2_messages_2")
        self.tab_gps_2.addTab(self.tab_gps_2_messages_2, "")
        self.tab_all.addTab(self.tab_gps, "")
        self.tab_depth = QtWidgets.QWidget()
        self.tab_depth.setObjectName("tab_depth")
        self.tab_depth_2 = QtWidgets.QTabWidget(self.tab_depth)
        self.tab_depth_2.setGeometry(QtCore.QRect(0, 0, 1231, 601))
        self.tab_depth_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_depth_2.setObjectName("tab_depth_2")
        self.tab_depth_2_data = QtWidgets.QWidget()
        self.tab_depth_2_data.setObjectName("tab_depth_2_data")
        self.tab_depth_2.addTab(self.tab_depth_2_data, "")
        self.tab_gps_2_messages_3 = QtWidgets.QWidget()
        self.tab_gps_2_messages_3.setObjectName("tab_gps_2_messages_3")
        self.tab_depth_2.addTab(self.tab_gps_2_messages_3, "")
        self.tab_all.addTab(self.tab_depth, "")
        self.tab_wt = QtWidgets.QWidget()
        self.tab_wt.setObjectName("tab_wt")
        self.tab_wt_2 = QtWidgets.QTabWidget(self.tab_wt)
        self.tab_wt_2.setGeometry(QtCore.QRect(0, 0, 1231, 601))
        self.tab_wt_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_wt_2.setObjectName("tab_wt_2")
        self.tab_wt_2_data = QtWidgets.QWidget()
        self.tab_wt_2_data.setObjectName("tab_wt_2_data")
        self.tab_wt_2.addTab(self.tab_wt_2_data, "")
        self.tab_wt_2_messages = QtWidgets.QWidget()
        self.tab_wt_2_messages.setObjectName("tab_wt_2_messages")
        self.tab_wt_2.addTab(self.tab_wt_2_messages, "")
        self.tab_all.addTab(self.tab_wt, "")
        self.tab_extrap = QtWidgets.QWidget()
        self.tab_extrap.setObjectName("tab_extrap")
        self.tab_extrap_2 = QtWidgets.QTabWidget(self.tab_extrap)
        self.tab_extrap_2.setGeometry(QtCore.QRect(0, 0, 1231, 601))
        self.tab_extrap_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_extrap_2.setObjectName("tab_extrap_2")
        self.tab_extrap_2_data = QtWidgets.QWidget()
        self.tab_extrap_2_data.setObjectName("tab_extrap_2_data")
        self.tab_extrap_2.addTab(self.tab_extrap_2_data, "")
        self.tab_wt_2_messages_2 = QtWidgets.QWidget()
        self.tab_wt_2_messages_2.setObjectName("tab_wt_2_messages_2")
        self.tab_extrap_2.addTab(self.tab_wt_2_messages_2, "")
        self.tab_all.addTab(self.tab_extrap, "")
        self.tab_edges = QtWidgets.QWidget()
        self.tab_edges.setObjectName("tab_edges")
        self.tab_edges_2 = QtWidgets.QTabWidget(self.tab_edges)
        self.tab_edges_2.setGeometry(QtCore.QRect(0, 0, 1231, 601))
        self.tab_edges_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_edges_2.setObjectName("tab_edges_2")
        self.tab_edges_2_data = QtWidgets.QWidget()
        self.tab_edges_2_data.setObjectName("tab_edges_2_data")
        self.tab_edges_2.addTab(self.tab_edges_2_data, "")
        self.tab_wt_2_messages_3 = QtWidgets.QWidget()
        self.tab_wt_2_messages_3.setObjectName("tab_wt_2_messages_3")
        self.tab_edges_2.addTab(self.tab_wt_2_messages_3, "")
        self.tab_all.addTab(self.tab_edges, "")
        self.horizontalLayout_4.addWidget(self.tab_all)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setMovable(True)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(70, 40))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/52.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/24x24/Application.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/images/24x24/Application.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOptions.setIcon(icon1)
        self.actionOptions.setObjectName("actionOptions")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/22.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionComment = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/24x24/Notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/images/24x24/Notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionComment.setIcon(icon3)
        self.actionComment.setObjectName("actionComment")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/24x24/Help book 3d.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon4)
        self.actionHelp.setObjectName("actionHelp")
        self.actionEDI = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.actionEDI.setFont(font)
        self.actionEDI.setObjectName("actionEDI")
        self.actionCheck = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/24x24/Red mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheck.setIcon(icon5)
        self.actionCheck.setObjectName("actionCheck")
        self.actionBT = QtWidgets.QAction(MainWindow)
        self.actionBT.setCheckable(False)
        self.actionBT.setChecked(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.actionBT.setFont(font)
        self.actionBT.setObjectName("actionBT")
        self.actionGGA = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.actionGGA.setFont(font)
        self.actionGGA.setObjectName("actionGGA")
        self.actionVTG = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.actionVTG.setFont(font)
        self.actionVTG.setObjectName("actionVTG")
        self.actionNav_Reference = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.actionNav_Reference.setFont(font)
        self.actionNav_Reference.setObjectName("actionNav_Reference")
        self.actionComp_Tracks = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.actionComp_Tracks.setFont(font)
        self.actionComp_Tracks.setObjectName("actionComp_Tracks")
        self.actionON = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.actionON.setFont(font)
        self.actionON.setObjectName("actionON")
        self.actionOFF = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.actionOFF.setFont(font)
        self.actionOFF.setObjectName("actionOFF")
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOptions)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionComment)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCheck)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEDI)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNav_Reference)
        self.toolBar.addAction(self.actionBT)
        self.toolBar.addAction(self.actionGGA)
        self.toolBar.addAction(self.actionVTG)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionComp_Tracks)
        self.toolBar.addAction(self.actionON)
        self.toolBar.addAction(self.actionOFF)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)

        self.retranslateUi(MainWindow)
        self.tab_all.setCurrentIndex(0)
        self.tab_summary.setCurrentIndex(0)
        self.tab_mc.setCurrentIndex(0)
        self.tab_systest_2.setCurrentIndex(1)
        self.tab_compass_2.setCurrentIndex(0)
        self.tab_tempsal_2.setCurrentIndex(0)
        self.tab_mtb_2.setCurrentIndex(1)
        self.tab_bt_2.setCurrentIndex(0)
        self.tab_gps_2.setCurrentIndex(1)
        self.tab_depth_2.setCurrentIndex(1)
        self.tab_wt_2.setCurrentIndex(1)
        self.tab_extrap_2.setCurrentIndex(1)
        self.tab_edges_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_summary.setTabText(self.tab_summary.indexOf(self.tab_summary_discharge), _translate("MainWindow", "Summary"))
        self.tab_summary.setTabText(self.tab_summary.indexOf(self.tab_summary_details), _translate("MainWindow", "Details"))
        self.label.setText(_translate("MainWindow", "Site Name: "))
        self.label_2.setText(_translate("MainWindow", "Site Number:"))
        self.tab_summary.setTabText(self.tab_summary.indexOf(self.tab_summary_premeasurement), _translate("MainWindow", "Premeasurement"))
        self.tab_summary.setTabText(self.tab_summary.indexOf(self.tab_summary_settings), _translate("MainWindow", "Settings"))
        self.tab_summary.setTabText(self.tab_summary.indexOf(self.tab_summary_adcp), _translate("MainWindow", "ADCP"))
        self.tab_mc.setTabText(self.tab_mc.indexOf(self.tab_mc_messages), _translate("MainWindow", "Messages"))
        self.tab_mc.setTabText(self.tab_mc.indexOf(self.tab_mc_comments), _translate("MainWindow", "Comments"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_main), _translate("MainWindow", "Main"))
        self.tab_systest_2.setTabText(self.tab_systest_2.indexOf(self.tab_systest_2_results), _translate("MainWindow", "Results"))
        self.box_systest_messages.setTitle(_translate("MainWindow", "Quality Check Messages"))
        self.box_systest_comments.setTitle(_translate("MainWindow", "Comments"))
        self.tab_systest_2.setTabText(self.tab_systest_2.indexOf(self.tab_systest_2_messages), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_systest), _translate("MainWindow", "SysTest"))
        self.cb_adcp_compass.setText(_translate("MainWindow", "ADCP Compass"))
        self.cb_ext_compass.setText(_translate("MainWindow", "Ext. Compass"))
        self.cb_mag_field.setText(_translate("MainWindow", "Mag. Field"))
        self.cb_pitch.setText(_translate("MainWindow", "Pitch"))
        self.cb_roll.setText(_translate("MainWindow", "Roll"))
        self.tab_compass_2.setTabText(self.tab_compass_2.indexOf(self.tab_compass_2_data), _translate("MainWindow", "Data"))
        self.groupBox_cal.setTitle(_translate("MainWindow", "Compass Calibration"))
        self.groupBox_eval.setTitle(_translate("MainWindow", "Compass Evaluation"))
        self.tab_compass_2.setTabText(self.tab_compass_2.indexOf(self.tab_compass_2_cal), _translate("MainWindow", "Calibration / Evaluation"))
        self.box_compass_messages.setTitle(_translate("MainWindow", "Quality Check Messages"))
        self.box_compass_comments.setTitle(_translate("MainWindow", "Comments"))
        self.tab_compass_2.setTabText(self.tab_compass_2.indexOf(self.tab_compass_2_messages), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_compass), _translate("MainWindow", "Compass/P/R"))
        self.tab_tempsal_2.setTabText(self.tab_tempsal_2.indexOf(self.tab_tempsal_2_data), _translate("MainWindow", "Data"))
        self.tab_tempsal_2.setTabText(self.tab_tempsal_2.indexOf(self.tab_tempsal_2_messages), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_tempsal), _translate("MainWindow", "Temp/Sal"))
        self.tab_mtb_2.setTabText(self.tab_mtb_2.indexOf(self.tab_mbt_2_data), _translate("MainWindow", "Data"))
        self.tab_mtb_2.setTabText(self.tab_mtb_2.indexOf(self.tab_mbt_2_messages), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_mbt), _translate("MainWindow", "MovBedTst"))
        self.tab_bt_2.setTabText(self.tab_bt_2.indexOf(self.tab_bt_2_data), _translate("MainWindow", "Data"))
        self.tab_bt_2.setTabText(self.tab_bt_2.indexOf(self.tab_bt_2_messages), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_bt), _translate("MainWindow", "BT"))
        self.tab_gps_2.setTabText(self.tab_gps_2.indexOf(self.tab_gps_2_data), _translate("MainWindow", "Data"))
        self.tab_gps_2.setTabText(self.tab_gps_2.indexOf(self.tab_gps_2_messages_2), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_gps), _translate("MainWindow", "GPS"))
        self.tab_depth_2.setTabText(self.tab_depth_2.indexOf(self.tab_depth_2_data), _translate("MainWindow", "Data"))
        self.tab_depth_2.setTabText(self.tab_depth_2.indexOf(self.tab_gps_2_messages_3), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_depth), _translate("MainWindow", "Depth"))
        self.tab_wt_2.setTabText(self.tab_wt_2.indexOf(self.tab_wt_2_data), _translate("MainWindow", "Data"))
        self.tab_wt_2.setTabText(self.tab_wt_2.indexOf(self.tab_wt_2_messages), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_wt), _translate("MainWindow", "WT"))
        self.tab_extrap_2.setTabText(self.tab_extrap_2.indexOf(self.tab_extrap_2_data), _translate("MainWindow", "Data"))
        self.tab_extrap_2.setTabText(self.tab_extrap_2.indexOf(self.tab_wt_2_messages_2), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_extrap), _translate("MainWindow", "Extrap"))
        self.tab_edges_2.setTabText(self.tab_edges_2.indexOf(self.tab_edges_2_data), _translate("MainWindow", "Data"))
        self.tab_edges_2.setTabText(self.tab_edges_2.indexOf(self.tab_wt_2_messages_3), _translate("MainWindow", "Messages"))
        self.tab_all.setTabText(self.tab_all.indexOf(self.tab_edges), _translate("MainWindow", "Edges"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Opens measurement data file(s)"))
        self.actionOptions.setText(_translate("MainWindow", "options"))
        self.actionOptions.setToolTip(_translate("MainWindow", "Optional Settings"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionComment.setText(_translate("MainWindow", "Comment"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionEDI.setText(_translate("MainWindow", "EDI"))
        self.actionCheck.setText(_translate("MainWindow", "UncheckAll"))
        self.actionBT.setText(_translate("MainWindow", "BT"))
        self.actionBT.setToolTip(_translate("MainWindow", "BT"))
        self.actionGGA.setText(_translate("MainWindow", "GGA"))
        self.actionGGA.setToolTip(_translate("MainWindow", "GGA"))
        self.actionVTG.setText(_translate("MainWindow", "VTG"))
        self.actionVTG.setToolTip(_translate("MainWindow", "VTG"))
        self.actionNav_Reference.setText(_translate("MainWindow", "Nav Reference:"))
        self.actionNav_Reference.setToolTip(_translate("MainWindow", "Nav Reference:"))
        self.actionComp_Tracks.setText(_translate("MainWindow", "Comp Tracks:"))
        self.actionON.setText(_translate("MainWindow", "ON"))
        self.actionOFF.setText(_translate("MainWindow", "OFF"))

import dsm_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

