# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wHOffset.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hoffset(object):
    def setupUi(self, hoffset):
        hoffset.setObjectName("hoffset")
        hoffset.resize(342, 155)
        self.gridLayout_2 = QtWidgets.QGridLayout(hoffset)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.hoffset_label = QtWidgets.QLabel(hoffset)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hoffset_label.setFont(font)
        self.hoffset_label.setObjectName("hoffset_label")
        self.horizontalLayout_2.addWidget(self.hoffset_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.ed_hoffset = QtWidgets.QLineEdit(hoffset)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ed_hoffset.setFont(font)
        self.ed_hoffset.setObjectName("ed_hoffset")
        self.horizontalLayout.addWidget(self.ed_hoffset)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gb_hoffset = QtWidgets.QGroupBox(hoffset)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_hoffset.setFont(font)
        self.gb_hoffset.setObjectName("gb_hoffset")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_hoffset)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_all = QtWidgets.QRadioButton(self.gb_hoffset)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rb_all.setFont(font)
        self.rb_all.setChecked(True)
        self.rb_all.setObjectName("rb_all")
        self.verticalLayout.addWidget(self.rb_all)
        self.rb_transect = QtWidgets.QRadioButton(self.gb_hoffset)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rb_transect.setFont(font)
        self.rb_transect.setObjectName("rb_transect")
        self.verticalLayout.addWidget(self.rb_transect)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.gb_hoffset)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(hoffset)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(hoffset)
        self.buttonBox.accepted.connect(hoffset.accept)
        self.buttonBox.rejected.connect(hoffset.reject)
        QtCore.QMetaObject.connectSlotsByName(hoffset)

    def retranslateUi(self, hoffset):
        _translate = QtCore.QCoreApplication.translate
        hoffset.setWindowTitle(_translate("hoffset", "Heading Offset"))
        self.hoffset_label.setText(_translate("hoffset", "Heading Offset"))
        self.gb_hoffset.setTitle(_translate("hoffset", "Apply To:"))
        self.rb_all.setText(_translate("hoffset", "All Transects"))
        self.rb_transect.setText(_translate("hoffset", "Transect Only"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hoffset = QtWidgets.QDialog()
    ui = Ui_hoffset()
    ui.setupUi(hoffset)
    hoffset.show()
    sys.exit(app.exec_())

