# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wOptions.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.resize(742, 167)
        self.gridLayout = QtWidgets.QGridLayout(Options)
        self.gridLayout.setObjectName("gridLayout")
        self.gb_units = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_units.setFont(font)
        self.gb_units.setObjectName("gb_units")
        self.rb_english = QtWidgets.QRadioButton(self.gb_units)
        self.rb_english.setGeometry(QtCore.QRect(20, 30, 82, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_english.setFont(font)
        self.rb_english.setChecked(True)
        self.rb_english.setObjectName("rb_english")
        self.rb_si = QtWidgets.QRadioButton(self.gb_units)
        self.rb_si.setGeometry(QtCore.QRect(20, 60, 82, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_si.setFont(font)
        self.rb_si.setObjectName("rb_si")
        self.gridLayout.addWidget(self.gb_units, 0, 0, 1, 1)
        self.gb_save_options = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_save_options.setFont(font)
        self.gb_save_options.setObjectName("gb_save_options")
        self.rb_All = QtWidgets.QRadioButton(self.gb_save_options)
        self.rb_All.setGeometry(QtCore.QRect(10, 30, 161, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_All.setFont(font)
        self.rb_All.setChecked(True)
        self.rb_All.setObjectName("rb_All")
        self.rb_checked = QtWidgets.QRadioButton(self.gb_save_options)
        self.rb_checked.setGeometry(QtCore.QRect(10, 60, 201, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_checked.setFont(font)
        self.rb_checked.setObjectName("rb_checked")
        self.gridLayout.addWidget(self.gb_save_options, 0, 1, 1, 1)
        self.gb_stylesheet = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_stylesheet.setFont(font)
        self.gb_stylesheet.setObjectName("gb_stylesheet")
        self.cb_stylesheet = QtWidgets.QCheckBox(self.gb_stylesheet)
        self.cb_stylesheet.setGeometry(QtCore.QRect(10, 40, 221, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb_stylesheet.setFont(font)
        self.cb_stylesheet.setObjectName("cb_stylesheet")
        self.gridLayout.addWidget(self.gb_stylesheet, 0, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 3)

        self.retranslateUi(Options)
        self.buttonBox.accepted.connect(Options.accept)
        self.buttonBox.rejected.connect(Options.reject)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", "Dialog"))
        self.gb_units.setTitle(_translate("Options", "Units"))
        self.rb_english.setText(_translate("Options", "English"))
        self.rb_si.setText(_translate("Options", "SI"))
        self.gb_save_options.setTitle(_translate("Options", "Save Options"))
        self.rb_All.setText(_translate("Options", "All Transects"))
        self.rb_checked.setText(_translate("Options", "Only Checked Transects"))
        self.gb_stylesheet.setTitle(_translate("Options", "Style Sheet"))
        self.cb_stylesheet.setText(_translate("Options", "Save style sheet with data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Options = QtWidgets.QDialog()
    ui = Ui_Options()
    ui.setupUi(Options)
    Options.show()
    sys.exit(app.exec_())

