# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wSOSSource.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sos_source(object):
    def setupUi(self, sos_source):
        sos_source.setObjectName("sos_source")
        sos_source.resize(360, 158)
        self.gridLayout_2 = QtWidgets.QGridLayout(sos_source)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_source = QtWidgets.QGroupBox(sos_source)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_source.setFont(font)
        self.gb_source.setObjectName("gb_source")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_source)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_internal = QtWidgets.QRadioButton(self.gb_source)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_internal.setFont(font)
        self.rb_internal.setObjectName("rb_internal")
        self.verticalLayout_2.addWidget(self.rb_internal)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb_user = QtWidgets.QRadioButton(self.gb_source)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_user.setFont(font)
        self.rb_user.setObjectName("rb_user")
        self.horizontalLayout_2.addWidget(self.rb_user)
        self.ed_sos_user = QtWidgets.QLineEdit(self.gb_source)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ed_sos_user.setFont(font)
        self.ed_sos_user.setObjectName("ed_sos_user")
        self.horizontalLayout_2.addWidget(self.ed_sos_user)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 4)
        self.horizontalLayout.addWidget(self.gb_source)
        self.gb_sos_source = QtWidgets.QGroupBox(sos_source)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_sos_source.setFont(font)
        self.gb_sos_source.setObjectName("gb_sos_source")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_sos_source)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_all = QtWidgets.QRadioButton(self.gb_sos_source)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rb_all.setFont(font)
        self.rb_all.setChecked(True)
        self.rb_all.setObjectName("rb_all")
        self.verticalLayout.addWidget(self.rb_all)
        self.rb_transect = QtWidgets.QRadioButton(self.gb_sos_source)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rb_transect.setFont(font)
        self.rb_transect.setObjectName("rb_transect")
        self.verticalLayout.addWidget(self.rb_transect)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.gb_sos_source)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(sos_source)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(sos_source)
        self.buttonBox.accepted.connect(sos_source.accept)
        self.buttonBox.rejected.connect(sos_source.reject)
        QtCore.QMetaObject.connectSlotsByName(sos_source)

    def retranslateUi(self, sos_source):
        _translate = QtCore.QCoreApplication.translate
        sos_source.setWindowTitle(_translate("sos_source", "Speed of Sound Source"))
        self.gb_source.setTitle(_translate("sos_source", "Speed of Sound Source"))
        self.rb_internal.setText(_translate("sos_source", " Internal (ADCP)"))
        self.rb_user.setText(_translate("sos_source", "User (m/s)"))
        self.gb_sos_source.setTitle(_translate("sos_source", "Apply To:"))
        self.rb_all.setText(_translate("sos_source", "All Transects"))
        self.rb_transect.setText(_translate("sos_source", "Transect Only"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sos_source = QtWidgets.QDialog()
    ui = Ui_sos_source()
    ui.setupUi(sos_source)
    sos_source.show()
    sys.exit(app.exec_())
