# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wSubsection.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_subsection(object):
    def setupUi(self, subsection):
        subsection.setObjectName("subsection")
        subsection.resize(420, 155)
        self.gridLayout_2 = QtWidgets.QGridLayout(subsection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.subsection_label = QtWidgets.QLabel(subsection)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.subsection_label.setFont(font)
        self.subsection_label.setObjectName("subsection_label")
        self.horizontalLayout_2.addWidget(self.subsection_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_label = QtWidgets.QLabel(subsection)
        self.start_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.start_label.setObjectName("start_label")
        self.horizontalLayout.addWidget(self.start_label)
        self.start_value = QtWidgets.QLineEdit(subsection)
        self.start_value.setObjectName("start_value")
        self.horizontalLayout.addWidget(self.start_value)
        self.start_units = QtWidgets.QLabel(subsection)
        self.start_units.setObjectName("start_units")
        self.horizontalLayout.addWidget(self.start_units)
        self.end_lable = QtWidgets.QLabel(subsection)
        self.end_lable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.end_lable.setObjectName("end_lable")
        self.horizontalLayout.addWidget(self.end_lable)
        self.end_value = QtWidgets.QLineEdit(subsection)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.end_value.setFont(font)
        self.end_value.setObjectName("end_value")
        self.horizontalLayout.addWidget(self.end_value)
        self.end_units = QtWidgets.QLabel(subsection)
        self.end_units.setObjectName("end_units")
        self.horizontalLayout.addWidget(self.end_units)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gb_hoffset = QtWidgets.QGroupBox(subsection)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_hoffset.setFont(font)
        self.gb_hoffset.setObjectName("gb_hoffset")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_hoffset)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_new = QtWidgets.QRadioButton(self.gb_hoffset)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rb_new.setFont(font)
        self.rb_new.setChecked(True)
        self.rb_new.setObjectName("rb_new")
        self.verticalLayout.addWidget(self.rb_new)
        self.rb_default = QtWidgets.QRadioButton(self.gb_hoffset)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.rb_default.setFont(font)
        self.rb_default.setObjectName("rb_default")
        self.verticalLayout.addWidget(self.rb_default)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.gb_hoffset)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(subsection)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(subsection)
        self.buttonBox.accepted.connect(subsection.accept)
        self.buttonBox.rejected.connect(subsection.reject)
        QtCore.QMetaObject.connectSlotsByName(subsection)

    def retranslateUi(self, subsection):
        _translate = QtCore.QCoreApplication.translate
        subsection.setWindowTitle(_translate("subsection", "Extrap Subsection"))
        self.subsection_label.setText(_translate("subsection", "Subsection in Percentage"))
        self.start_label.setText(_translate("subsection", "Start"))
        self.start_units.setText(_translate("subsection", "%"))
        self.end_lable.setText(_translate("subsection", "End"))
        self.end_units.setText(_translate("subsection", "%"))
        self.gb_hoffset.setTitle(_translate("subsection", "Apply To:"))
        self.rb_new.setText(_translate("subsection", "Apply"))
        self.rb_default.setText(_translate("subsection", "Default (0 / 100 %)"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    subsection = QtWidgets.QDialog()
    ui = Ui_subsection()
    ui.setupUi(subsection)
    subsection.show()
    sys.exit(app.exec_())
